sphinxのアップロード先と条件の変更
sbgisen/.github pull request #107
Opened 2022-06-16 09:03 UTC by anna-ss

## Summary
- sphinxのドキュメントについて、gh-pagesブランチへのpushではなく、AWSのS3にアップロードするように変更しました
- 条件を以下のように変更しています。
  - ドキュメントのビルド→./docs/_sources/conf.pyの存在（従来通り）
  - ドキュメントのアップロード→デフォルトブランチへのpush＆ビルドの成功
- secretsが増えているため、動作させるにはcube_python_api側の改修も必要です。（pull request作成後追記）
- fix #99

## Test
- cube_python_api内のワークフローを、実行条件を開発ブランチのpushにして実行
  - テストのため、デフォルトブランチでなくても実行できるように.github/workflow/ros-build.ymlの`Install AWS CLI`について、条件`github.event.repository.default_branch == github.ref_name &&`をコメントアウト→[結果](https://github.com/sbgisen/cube_python_api/runs/6913830908?check_suite_focus=true)
  - 上記の部分のコメントアウトは外し、ビルドまでで止まることを確認→[結果](https://github.com/sbgisen/cube_python_api/runs/6915199568?check_suite_focus=true)

## Attention

s3のアップロード先フォルダはリポジトリ名としていますが、docs.cuboid.cloudに公開するには、別途AWS側の設定が必要になります。
（cube_python_api以外で利用した際に上書きを防ぐため、フォルダが別れるようにしています）

2022-06-17 02:13 UTC, anna-ss commented on .github/workflows/ros-build.yml
> +          sphinx-build docs/_sources/. docs/_build/.
/.はsphinx-buildのサンプルから持ってきただけで、特に理由はありません。
テストをしてみて、問題なければ外そうかと思います。

2022-06-17 04:26 UTC, anna-ss commented
ご指摘部分を修正し、動作確認を行いました。ご確認をお願いいたします。

- if条件`github.event.repository.default_branch == github.ref_name`なし（S3へのPublishあり）
https://github.com/sbgisen/cube_python_api/runs/6929438655?check_suite_focus=true
- if条件`github.event.repository.default_branch == github.ref_name`あり（S3へのPublishなし）
https://github.com/sbgisen/cube_python_api/runs/6929572351?check_suite_focus=true

2022-06-17 06:28 UTC, Tacha-S requested changes

2022-06-17 06:28 UTC, Tacha-S commented on .github/workflows/ros-build.yml
> +        uses: jakejarvis/s3-sync-action@master
このアクションの内容をある程度確認した上で問題なければそのコミットのSHAで固定してください
https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions

2022-06-17 08:07 UTC, anna-ss commented on .github/workflows/ros-build.yml
> +        uses: jakejarvis/s3-sync-action@master
確認したところ、pythonのdockerでaws-cliをインストールし、コマンドを実行しているだけなので大丈夫そうです。（補足ですが、github actionのubuntu-18.04だとデフォルトでaws-cliが入っているため、marketplaceのactionは不要になります。今回はインストールが必要になるため、こちらのactionを使いたいと思います）
動作確認をした最新版で、バージョンの固定を行いました。

2022-06-17 08:26 UTC, Tacha-S approved these changes

2022-06-17 08:29 UTC, Tacha-S requested changes
すみません追加でもう一つ
READMEにcube_docs_aws_access_key_idとcube_docs_aws_secret_access_keyがoptionalでドキュメントをデプロイする際に必要ってことを追記お願いします。

2022-06-17 08:48 UTC, anna-ss commented
@Tacha-S 追記しました。ご確認をお願いいたします。

2022-06-20 00:02 UTC, Tacha-S approved these changes

2022-06-20 00:02 UTC, merged