Deploy to GitHub Pages
sbgisen/.github pull request #122
Opened 2022-10-05 11:07 UTC by Tacha-S

## Summary

デプロイ先をS3からGitHub Pagesに変更

- fix #120 

## Detail

このデプロイ方法を有効にするには、
有効にしたいリポジトリでSettings->PagesからsourceをGitHub Actionsにする必要があります。
またSettings->Environmentsにてブランチのルール等が正しく設定されているかを確認してください。

## Impact

## Test

  

## Attention

2022-10-06 00:33 UTC, jsupratman13 requested changes

2022-10-06 00:33 UTC, jsupratman13 commented on .github/workflows/ros-build.yml
> +          echo "::set-output name=file_exists::$(find . -wholename ./docs/_build/index.html | wc -l)"
確認ですが、
ubuntu 18.04でsphinx失敗しても(ビルド成功しても正しいファイルが生成しない時)index.htmlを生成していたのでpy-modindex.htmlで確認していましたが、ubuntu 20.04は正しいファイルが生成しない時にindex.htmlを生成しない仕様になったのですか？

2022-10-06 00:38 UTC, Tacha-S commented on .github/workflows/ros-build.yml
> +          echo "::set-output name=file_exists::$(find . -wholename ./docs/_build/index.html | wc -l)"
そういう経緯だったんですね

2022-10-06 00:43 UTC, Tacha-S commented on .github/workflows/ros-build.yml
> +          echo "::set-output name=file_exists::$(find . -wholename ./docs/_build/index.html | wc -l)"
正しいファイルが生成しない時ってどんなときですか

2022-10-06 00:49 UTC, Tacha-S commented on .github/workflows/ros-build.yml
> +          echo "::set-output name=file_exists::$(find . -wholename ./docs/_build/index.html | wc -l)"
conf.pyでpythonの構文的にエラーを出させるとそもそも何も_buildには配置されないです。

2022-10-06 01:32 UTC, jsupratman13 commented on .github/workflows/ros-build.yml
> +          echo "::set-output name=file_exists::$(find . -wholename ./docs/_build/index.html | wc -l)"
> sphinx-autobuildでwarningが出る程度だとpy-modindexも生成されるんですが、 正しいファイルが生成しない時ってどんなときですか

同時初期の頃sphinxとgithub page周りで色々なことを（特にどの段階で自動生成するかなどを）試していたので自分の環境・テストベットが悪さしているかもしれませんが、sphinx-apidocが正しくないrstファイルを生成したり、rstまたはconf.pyに正しくないをパス指定してビルドするとpy-modindexが生成しない問題がよく起きていました。

2022-10-06 01:39 UTC, jsupratman13 commented on .github/workflows/ros-build.yml
> +          echo "::set-output name=file_exists::$(find . -wholename ./docs/_build/index.html | wc -l)"
一番分かりやすい再現方法は
ドキュメント生成する前の状態に戻しsphinx-apidocを実行せず sphinx-(auto)buildするとページがビルドできるけがどこにもいけないページができる

2022-10-06 01:52 UTC, jsupratman13 commented on .github/workflows/ros-build.yml
> +          echo "::set-output name=file_exists::$(find . -wholename ./docs/_build/index.html | wc -l)"
> > 一番分かりやすい再現方法は ドキュメント生成する前の状態に戻しsphinx-apidocを実行せず sphinx-(auto)buildするとページがビルドできるけがどこにもいけないページができる
> 
> たしかにこれはほぼ空のページができるんですが、そもそもでsphinx-apidocを実行せず(もしくはsphinx-apidocが失敗する)状況はCI的にエラーで落ちるわけですし、 GitHub Pagesとしてもサイトを公開する上で必要なのはindex.htmlでありpymodindex.htmlではないので、 sphinx-autobuildで検出できないエラーでない限りpymodindex.htmlを指定するのは不適当だとおもいます。

それでいいと思います。

2022-10-06 03:00 UTC, anna-ss commented
https://docs.cuboid.cloud/cube_python_api/
@h-wata 
s3へのpushがなくなりますが、上のURLも今後廃止でよいでしょうか？
Cuboidで開発を行う外部の方へcube_python_apiのドキュメントを展開するため、上の場所に配置した記憶ですが、github pagesへの配置の場合はgithub enterpriseへの加入が必要になります。その運用で問題ないですか？

2022-10-07 01:52 UTC, h-wata commented
sbgisenのoutside collaboratorの方が見られれば良いのですが、みられないんでしたっけ?

2022-10-07 01:57 UTC, Tacha-S commented
sbgisenのoutside collaborator(厳密に言うとそのページを公開しているリポジトリの閲覧権限を持つ人)は見られます。
@anna-ss はこのoutside collaboratorにも入れる前の段階を危惧しているように見えますが、
開発者向けのドキュメントはそのリポジトリを見れる(outside collaboratorになる)ようになってから必要かと思っていました。

2022-10-07 01:59 UTC, h-wata commented
![image](https://user-images.githubusercontent.com/20681658/194450330-c7cde135-b5e6-4a99-b445-300e66cddf2c.png)

@Tacha-S ありがとうございます。自分も確認できました。
権限を付与されている方が見れるので十分かと思います。なのでS3じゃなくて、github pagesで良いと思います。

2022-10-07 02:01 UTC, h-wata approved these changes

2022-10-07 02:02 UTC, Tacha-S commented
@anna-ss 一時的とはなってしまいましたがAWSのほうでの公開対応ありがとうございました。:bow:

2022-10-07 02:03 UTC, jsupratman13 commented
@anna-ss ありがとうございます！

2022-10-07 02:04 UTC, anna-ss approved these changes
collaboratorの方に向けて公開する旨、承知しました。
cube-docsの方は後日リンクを削除しておきます。よろしくお願いいたします。

2022-10-07 02:07 UTC, merged