add steps to build and publish documentations
sbgisen/.github pull request #83
Opened 2022-04-05 09:53 UTC by jsupratman13

## Summary
* resolves #82 
* 条件を満たすとドキュメントを自動生成するステップを追加
* `gh_pages`のブランチにドキュメントが出てくるだけなので、github pagesなど使いたい場合、手動で設定する必要がある

## Detail
1. レポジトリに`<ROS レポジトリ>/docs/_sources/conf.py`ファイルが存在したらドキュメントを生成するステップを実行
   1. sphinxの依存関係をインストール
       * `docs/_sources/requirements.txt`で追加パッケージをインストール可能 (例：sphinxのテーマなど)
   2. google/numpy style docstring -> RestructredText に変換 (sphinx-apidocを実行)
       * `doc_module_path`オプションでモジュールパスを指摘可能
   4. ドキュメントをビルドする
5. デフォルトブランチにプッシュした後に、生成したドキュメントを、`gh_pages`ブランチにプッシュするステップを実行

## Impact

## Test
  * [ ] catkin buildを通った
  * [ ] gazebo環境で起動した
    * [ ] cuboid
    * [ ] signage
  * [ ] 実機環境で起動した
    * [ ] cuboid
    * [ ] signage
  * [ ] (アプリ名)で動作検証した

## refs

## 補足

2022-04-05 10:16 UTC, Tacha-S requested changes

2022-04-05 10:16 UTC, Tacha-S commented on .github/workflows/ros-build.yml
> +      - name: Generate documentations
ここまで粒度分けなくても上のstepとまとめて1 stepでいいと思います。

2022-04-05 10:16 UTC, Tacha-S commented on .github/workflows/ros-build.yml
> +          pip2 install bs4
requirements.txtにまとめていない理由は何ですか？

2022-04-05 10:16 UTC, Tacha-S commented on .github/workflows/ros-build.yml
> +          apt-get install -y python-pip
buildのworkflowではdistroでnoeticを選べるようにしているんで、こんな感じでpython3に対応してほしいです。
https://github.com/sbgisen/.github/blob/e6b5507222f88b02c524d273affa59b7760f977d/.github/workflows/ros-build.yml#L137-L141

ここからはOptionalでこちらでやってもいいですが、
できればbuildの最初の方でこれをdistroに合わせてversion変えられるとなおいいです。
https://github.com/sbgisen/.github/blob/e6b5507222f88b02c524d273affa59b7760f977d/.github/workflows/linter_ros_package.yaml#L89-L92

2022-04-05 10:16 UTC, Tacha-S commented on .github/workflows/ros-build.yml
> +        shell: bash -leo pipefail {0}
`-leo pipefail {0}` 要らないです。というかdocker環境なのでそもそも.bashrc特に何も書かれていないと思います。

2022-04-05 10:16 UTC, Tacha-S commented on .github/workflows/ros-build.yml
> +          if [ `find . -wholename ./docs/_sources/conf.py | wc -l` -eq 0 ]; then
findの終了ステータスを使わずに行数確認しに行っているのは何か理由がありますか？

2022-04-05 10:16 UTC, Tacha-S commented on .github/workflows/ros-build.yml
> +        uses: peaceiris/actions-gh-pages@v3
3rd packageのactionかつtokenを渡してしまうので、
内部でどんな処理をしているのかを確認した上で、本当に指定したブランチへのpushのみしていればそのcommit hashに変更してください。

例
https://github.com/sbgisen/.github/blob/e6b5507222f88b02c524d273affa59b7760f977d/.github/workflows/ros-build.yml#L55

2022-04-05 10:16 UTC, Tacha-S commented on .github/workflows/ros-build.yml
> +          github_token: ${{ secrets.GITHUB_TOKEN }}
明確に`secrets.GITHUB_TOKEN`でなければいけない理由がなければ、
統一の意味も含めて`github.token`を使ってください。
https://github.com/sbgisen/.github/blob/e6b5507222f88b02c524d273affa59b7760f977d/.github/workflows/ros-test.yml#L160

2022-04-05 10:21 UTC, jsupratman13 commented on .github/workflows/ros-build.yml
> +        description: "Specify module path for sphinx-apidoc."
scriptsフォルダに入っているファイルかな？例えばステートマシンなどドキュメントしたい場合など考えていましたがやはり必要ない？

2022-04-05 10:24 UTC, jsupratman13 commented on .github/workflows/ros-build.yml
> +          pip2 install bs4
1. sphinxのテーマ
2. conf.pyに追加機能を加える時にの追加パッケージなど

2022-04-05 10:27 UTC, jsupratman13 commented on .github/workflows/ros-build.yml
> +          github_token: ${{ secrets.GITHUB_TOKEN }}
ok

2022-04-05 10:36 UTC, jsupratman13 commented on .github/workflows/ros-build.yml
> +          if [ `find . -wholename ./docs/_sources/conf.py | wc -l` -eq 0 ]; then
https://github.com/sbgisen/.github/blob/e6b5507222f88b02c524d273affa59b7760f977d/.github/workflows/ros-build.yml#L134

上記のステップをコピーしました。CMakeLists.txtの存在を行数を確認する仕組みだと思っていましたが、別の理由でしたら修正しておきます。

2022-04-05 10:36 UTC, jsupratman13 commented on .github/workflows/ros-build.yml
> +        shell: bash -leo pipefail {0}
ok

2022-04-05 10:43 UTC, jsupratman13 commented on .github/workflows/ros-build.yml
> +      - name: Generate documentations
ok

2022-04-05 10:57 UTC, jsupratman13 commented on .github/workflows/ros-build.yml
> +        uses: peaceiris/actions-gh-pages@v3
確認したところヤバそうなところは見当たりませんが、github actionについてまだ知識が浅いのでどんなところを注目した方がいいでしょうか？

2022-04-05 23:53 UTC, Tacha-S commented on .github/workflows/ros-build.yml
> +        description: "Specify module path for sphinx-apidoc."
そういうことであれば、ROSパッケージの構成的にdefaultでsrcとscriptsに対してsphinx-apidoc実行するべきだと思います。optionは要らないです。

2022-04-05 23:56 UTC, Tacha-S commented on .github/workflows/ros-build.yml
> +          pip2 install bs4
これはrequirements.txtには1,2のみを含むと言いたいですか？
だとしたらbs4はなぜここに？

2022-04-06 00:02 UTC, Tacha-S commented on .github/workflows/ros-build.yml
> +          if [ `find . -wholename ./docs/_sources/conf.py | wc -l` -eq 0 ]; then
findがディレクトリさえあればexit code 0なの忘れてました。
CMakeLists.txtの検索はメタパッケージ等だとpathが不確定なのでfind使ってますが、
conf.pyはpathが明確なのであれば、`if [ -f "./docs/_sources/conf.py" ]; then`でいいです。

2022-04-06 00:13 UTC, Tacha-S commented on .github/workflows/ros-build.yml
> +        uses: peaceiris/actions-gh-pages@v3
action.yamlを見て、このindex.jsを起点にだいたいどんなことをしているか、repositoryの中を不用意にいじったり、repositoryをどこかにコピーされていないか等(private repositoryでも実行されるため)。

2022-04-06 00:25 UTC, Tacha-S commented on .github/workflows/ros-build.yml
> +          force_orphan: true
`force_orphan`は有効にしないといけないですか？

2022-04-06 00:27 UTC, jsupratman13 commented on .github/workflows/ros-build.yml
> +          pip2 install bs4
自分の環境でsphinx-buildを実行する時にbs4がimportできない問題があったのでbs4をインストールすることで解決しましたが、こちらについてはもう一度確認しておきます。

2022-04-06 00:32 UTC, Tacha-S commented on .github/workflows/ros-build.yml
> +          pip2 install bs4
たぶん、ROS Messageのinventry作るときのscriptで必要なだけだと思うので2.に該当すると思います。
https://github.com/sbgisen/cube_python_api/blob/1aee0f8d052ed158bbd4480e533b5aa6ddfdb92a/docs/source/conf.py#L54

2022-04-06 00:33 UTC, jsupratman13 commented on .github/workflows/ros-build.yml
> +          force_orphan: true
いや特に。
デバッグ中最新のコミットのみ欲しかったので有効にしましたが、コミットあった方がいいなら無効にします。

2022-04-06 00:34 UTC, jsupratman13 commented on .github/workflows/ros-build.yml
> +          if [ `find . -wholename ./docs/_sources/conf.py | wc -l` -eq 0 ]; then
ok
修正しておきます。

2022-04-06 00:40 UTC, Tacha-S commented on .github/workflows/ros-build.yml
> +          force_orphan: true
このactionが生成したコミットのみかにかかわらず`publish_branch`にforce pushしているので、もし独自にこのブランチを用意していた際に履歴飛ばしてしまう可能性があるので少し危険だと思います。
なくても大丈夫なのであれば無効にしたほうがいいと思います。

2022-04-06 00:41 UTC, jsupratman13 commented on .github/workflows/ros-build.yml
> +          if [ `find . -wholename ./docs/_sources/conf.py | wc -l` -eq 0 ]; then
ちなみに`if [ -f "./docs/_sources/conf.py" ]; then` の`-f`は初めてみましたがこれは何かのbashの特集コマンドですか？

2022-04-06 00:48 UTC, Tacha-S commented on .github/workflows/ros-build.yml
> +          if [ `find . -wholename ./docs/_sources/conf.py | wc -l` -eq 0 ]; then
`[ ]`がtestコマンドを実行しているんですが、そのtestコマンドの`-f`オプションがファイルかどうかを確認するものになってます。
https://linux.die.net/man/1/test

2022-04-06 01:01 UTC, jsupratman13 commented on .github/workflows/ros-build.yml
> +        description: "Specify module path for sphinx-apidoc."
optionsを外しておきますが、
> ROSパッケージの構成的にdefaultでsrcとscriptsに対してsphinx-apidoc実行するべきだと思います。

これについてsrc/とscripts/を両方ともモジュール扱いするの？

2022-04-06 01:02 UTC, jsupratman13 commented on .github/workflows/ros-build.yml
> +          force_orphan: true
ok 修正しておきます。

2022-04-06 01:07 UTC, jsupratman13 commented on .github/workflows/ros-build.yml
> +          pip2 install bs4
これだ
見逃していました。
修正しておきます。

2022-04-06 01:14 UTC, Tacha-S commented on .github/workflows/ros-build.yml
> +        description: "Specify module path for sphinx-apidoc."
scriptsにdocstringの書いてあるpythonファイルがあればモジュールとして扱いたいっていう話だと思ったのでそう思ったんですが、そうじゃなかったですか？

2022-04-06 02:40 UTC, jsupratman13 commented on .github/workflows/ros-build.yml
> +        description: "Specify module path for sphinx-apidoc."
ちゃんと覚えていないけどそうかも。

今考えるとROSパッケージ構成的にscriptsはモジュールを置くところじゃなにので省いていいかも。

2022-04-06 02:55 UTC, Tacha-S commented on .github/workflows/ros-build.yml
> +        description: "Specify module path for sphinx-apidoc."
scriptsに関しては必要であればrstを手動で作成するということね

2022-04-06 03:00 UTC, jsupratman13 commented on .github/workflows/ros-build.yml
> +        description: "Specify module path for sphinx-apidoc."
`__init__.py`をrootとscriptsに入れるならいいけどおっしゃる通りscriptsに関しては必要であればrstを手動にする方向

2022-04-06 03:02 UTC, jsupratman13 commented on .github/workflows/ros-build.yml
> +          apt-get install -y python-pip
現段階でnoetic distro/ubuntu 20.04上のドキュメント生成はまだ未検証なので今回はmelodicの場合ドキュメント生成する・noeticの場合ドキュメント生成しない形で大丈夫でしょうか？

2022-04-06 03:09 UTC, Tacha-S commented on .github/workflows/ros-build.yml
> +          apt-get install -y python-pip
ではnoetic環境でのドキュメント生成のissue作っておいてください。

2022-04-06 05:35 UTC, jsupratman13 commented on .github/workflows/ros-build.yml
> +        uses: peaceiris/actions-gh-pages@v3
commit hashに変更しましたかつactionの内部処理を確認しました

2022-04-06 06:59 UTC, Tacha-S approved these changes

2022-04-06 06:59 UTC, merged